import "./global.css";
import 'keen-slider/keen-slider.min.css'

import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import { MenuNav } from "./components/MenuNav";
import { Footer } from "./components/Footer";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/vds.png" sizes="any" />

      <body className={raleway.className}>
        <MenuNav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
